name: Build Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html
          

      # - name: Commit and push updated documentation
      #   run: |
      #     cd docs/_build/latex
      #     if [ -f "YourDocumentation.pdf" ]; then
      #       git config --local user.email "action@github.com"
      #       git config --local user.name "GitHub Action"
      #       git add YourDocumentation.pdf
      #       git commit -m "Update documentation PDF"
      #       git push origin HEAD:main
      #     else
      #       echo "No changes in documentation."
      #     fi
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
