name: Python package tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (pip)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dependencies (conda)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          conda env create --file environment.yml
          conda activate acsefunctions

      - name: Run Python tests
        run: |
          pytest tests/

      - name: Run flake8 linter
        run: |
          flake8 acsefunctions

      - name: Validate conda environment.yml
        if: matrix.os == 'windows-latest'
        run: |
          conda env create --file environment.yml --dry-run

      - name: Validate pip requirements.txt
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip check
