name: Python package tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Pytest and Flake8 on multiple OSes
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 as per your example

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install dependencies via pip for both OSes
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests with pytest
      - name: Test with pytest
        run: |
          pytest tests/

      # Run flake8 linter
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 acsefunctions --max-line-length=100

  validate_conda:
    name: Validate conda environment.yml on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install and validate conda
        run: |
          conda env create --file environment.yml --dry-run
