name: Python package tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10']  # Using both Python 3.9 and 3.10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Install Miniconda for both Ubuntu and Windows
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}  # Use the correct Python version for each job
          activate-environment: acsefunctions  # Automatically activate the environment
          environment-file: base-environment.yml    # Install only base dependencies
          auto-activate-base: false            # Avoid activating base environment by default

      # Install additional environment dependencies (Linux)
      - name: Install extra conda dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          conda env update --file extra-environment.yml

      # Install pip dependencies (Linux)
      - name: Install base dependencies with pip (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install --upgrade pip
          pip install -r base-requirements.txt

      - name: Install extra pip dependencies with pip (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install -r extra-requirements.txt

      - name: Run Python tests
        run: |
          pytest tests/

      - name: Run flake8 linter
        run: |
          flake8 acsefunctions

      - name: Validate conda base environment.yml (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          conda env create --file base-environment.yml --dry-run

      - name: Validate conda extra environment.yml (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          conda env create --file extra-environment.yml --dry-run

      - name: Validate pip base requirements.txt (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip check -r base-requirements.txt

      - name: Validate pip extra requirements.txt (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip check -r extra-requirements.txt
